---


- name: Get timestamp from control node.
  # connection: local
  ansible.builtin.set_fact:
    _timestamp: "{{ lookup('ansible.builtin.pipe', 'date +%Y%m%d') }}"
  delegate_to: "{{ fortigate_backup_bastion }}"

- name: Make sure backup dir exist.
  # connection: local
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fortigate_backup_files_owner }}"
    group: "{{ fortigate_backup_files_group }}"
    mode: "744"
  delegate_to: "{{ fortigate_backup_bastion }}"
  loop:
    - "{{ fortigate_backup_files_path }}"
    - "/tmp/fortigate_backup/{{ _timestamp }}"
  run_once: true
